### PR TITLE
Added typst-live

### PR DESCRIPTION
**Pull request by ItsEthra**
This pr adds `typst-live` project. It has a subtle difference from `--watch` flag of the official cli tool, `typst-live` hot reloads(automatically refreshes webpage) pdf file in browser whenever source files change.

### CODE REVIEW

**Comment by qjcg** [comment]
Thanks for this awesome contribution @ItsEthra !

**Comment by ItsEthra** [comment]
@qjcg hey, do you mind me asking why you have removed it from the list?

**Comment by qjcg** [comment]
@ItsEthra It was a completely unintentional mistake! Have re-added and pushed to main. My apologies!

**Comment by ItsEthra** [comment]
Alright no worries

**Pull request merged**
